In [1]:
# import tensorflow
# pip install tensorflow
# pip show tensorflow
# pip install keras
import keras

In [2]:
import cv2

In [3]:
import os
from keras.preprocessing import image
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
categories = ['with_mask','without_mask']
datadir = "D:\Data Science Project\Face Mask Detection\data"

In [5]:
data=[]
for category in categories:
    path = os.path.join(datadir,category)
#     print(path)
    
    label = categories.index(category)
#     print(label)
    
    
    for file in os.listdir(path):
#         print(file)
# # #         break
        img_path = os.path.join(path,file)
#         print(img_path)
        img =cv2.imread(img_path)
#         print(img)
        img =cv2.resize(img,(224,224))
#         print(img)
#         img = img[0]
#         print(img.shape)
        data.append([img,label])

# print(data)

In [6]:
len(data)


1376

In [7]:
# shaffle the data

In [8]:
import random
random.shuffle(data)

### Split into X & Y

In [9]:
X = []
Y = []
for features,label in data:
    X.append(features) #2d
    Y.append(label)  # 1d

In [10]:
print(len(X))
print(len(Y))

1376
1376


In [11]:

print(Y)

[1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 

In [12]:
print(X)     

[array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8), array([[[150, 180, 205],
        [152, 183, 208],
        [152, 184, 209],
        ...,
        [160, 160, 158],
        [162, 162, 161],
        [165, 164, 166]],

       [[150, 180, 205],
        

In [13]:
x = np.array(X)
y = np.array(Y)
# print(x)

In [14]:
print(y)
print(x.shape)
print(y.shape)

[1 1 0 ... 1 0 1]
(1376, 224, 224, 3)
(1376,)


In [15]:
# x scaling
x=x/255

In [16]:
print(x[0])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
print(y)

[1 1 0 ... 1 0 1]


### Splite into train and test data

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [19]:
print(x_train.shape)
print(y_train.shape)

(1100, 224, 224, 3)
(1100,)


In [20]:
print(x_test.shape)

(276, 224, 224, 3)


### Import VGG16

In [21]:
from keras.applications import VGG16
vgg=VGG16()

In [22]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [23]:
from keras import Sequential
from keras import layers
model=Sequential()

### Remove prediction layer

In [24]:
for layer in vgg.layers[:-1]:
    model.add(layer)

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [26]:
for layer in model.layers:
    layer.trainable = False

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

### Adding last layer

In [28]:
model.add(layers.Dense(1,activation='sigmoid'))

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [30]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [31]:
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
35/35 [==============================] - 613s 18s/step - loss: 0.6122 - accuracy: 0.6927 - val_loss: 0.4969 - val_accuracy: 0.7210
Epoch 2/5
35/35 [==============================] - 616s 18s/step - loss: 0.3612 - accuracy: 0.8945 - val_loss: 0.2779 - val_accuracy: 0.9203
Epoch 3/5
35/35 [==============================] - 616s 18s/step - loss: 0.2629 - accuracy: 0.9345 - val_loss: 0.2190 - val_accuracy: 0.9420
Epoch 4/5
35/35 [==============================] - 614s 18s/step - loss: 0.2230 - accuracy: 0.9373 - val_loss: 0.1860 - val_accuracy: 0.9457
Epoch 5/5
35/35 [==============================] - 613s 18s/step - loss: 0.1912 - accuracy: 0.9445 - val_loss: 0.1632 - val_accuracy: 0.9529


In [32]:
cap = cv2.VideoCapture(0)

### Prediction

In [38]:
def detect_face_mask(img):
    
    y_pred =  np.round(model.predict(img.reshape(1,224,224,3)))
    
    if y_pred[0][0] == 0:
        print("With Mask")
    else:
        print("Without Mask")
    
#     return y_pred[0][0]

In [39]:
sample1 = cv2.imread('sample/1.jpg')
sample1 = cv2.resize(sample1,(224,224))

In [40]:
detect_face_mask(sample1)

1/1 [==============================] - 1s 605ms/step
With Mask


In [41]:
sample2 = cv2.imread('sample/2.jpg')
sample2 = cv2.resize(sample2,(224,224))
detect_face_mask(sample2)

1/1 [==============================] - 1s 568ms/step
Without Mask


In [42]:
sample2 = cv2.imread('sample/3.jpg')
sample2 = cv2.resize(sample2,(224,224))
detect_face_mask(sample2)

1/1 [==============================] - 1s 583ms/step
Without Mask


In [43]:
sample2 = cv2.imread('sample/5.jpg')
sample2 = cv2.resize(sample2,(224,224))
detect_face_mask(sample2)

1/1 [==============================] - 1s 569ms/step
With Mask
